# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2da092c3be4b236d6e2ae3d75255cd6d"
name = "vaildate-cart-basic"
handle = "vaildate-cart-basic"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false
